#
# build property setting
#

#java compiler properties
compiler.debug.option 				= on
compiler.deprecation.option 		= off

# project directory properties
project.home.dir	= ../
project.name		= yd
project.lib			= lib
project.hsteelApp	= hsteelApp
project.jspeedApp	= jspeed
project.build		= build

# xdoclet compiler properties

xdoclet.enc        	= euc-kr
xdoclet.force		= true
xdoclet.verbose		= true
xdoclet.version		= 1.0
xdoclet.ejbspec		= 2.0
xdoclet.template	= xdoclet.template

# directory properties
dist         = dist
dist_new    = dist_new
src          = src
gensrc       = gensrc
classes      = classes
meta-inf.dir = META-INF

